### ISSUE TITLE
Support Python 3.10

### ISSUE THREAD

**Issue by john-science** [john-science/mazelib#120]
The new version of the language is out, and NumPy says they support it.

So let's give it a try.

If it works, this will also require a release to PyPI.

**Comment by john-science** [comment]
The major issue here is (at least on Debian-based OSs), Python 3.10 no longer comes with `distutils`.  Which would be fine, but it is a hard breaking change on PIP and VirtualEnv.

I assume this is solvable. But honestly, the Python team have not provided any guidance on how to use the new language version, and a bunch of searching online just show people hand-installing the PIP version from Python3.8 from binaries and zips and things.

So there is not a clean solution to move forward with Python 3.10 that I see.  I will have to take another whack at it. But this is just a big middle finger from the Python dev team.

**Comment by john-science** [comment]
The Problem: the Python dev team removed `distutils`, and it broke PIP and VirtualEnv on most major Linux platforms:

https://github.com/pypa/get-pip/issues/124

**Comment by john-science** [comment]
Travis does not seem to support Python 3.10 in the same way as with other Python versions:

https://app.travis-ci.com/github/john-science/mazelib/jobs/553005530

**Comment by debnet** [comment]
Any news about supporting Python 3.10? :)

**Comment by john-science** [comment]
> Any news about supporting Python 3.10? :)

I haven't tried since the new year.  The major problem is that the Python language team has removed `distutils` from the standard library, which breaks backwards compatibility.  (If you remember the Python v2 to v3 transition, this is like that.)

I would like it if there was some standard way to move forward, but I haven't had time to see what other people are doing. Do you know what solutions people are using?

I can do a little more research after work this week.  It's annoying that the Python team did this to us, but I'm sure there are work-arounds. I probably just have to change the build process in the project.

**Comment by debnet** [comment]
According to the changelog documentation, you have to rely on `setuptools` and `packaging` third-party packages to do what you need. They are already well-known by the community and are often used as dependancies for building packages.

**Comment by john-science** [comment]
@debnet Please note: Mazelib now supports Python 3.10:  https://pypi.org/project/mazelib/0.9.13/#description

I had to switch from TravisCI to GitHub Actions for this project to do it, but it works now.
