### ISSUE TITLE
Struggling to generate a maze

### ISSUE THREAD

**Issue by comalley29** [john-science/mazelib#125]
Hi, john-science, thank you for making this whole library, I'm struggling to use the package to make a maze. can you give me any advice.

**Comment by john-science** [comment]
Hey there,

Have you tried reading the docs?

https://github.com/john-science/mazelib/blob/master/docs/API.md

The first suggestion is:

```python
from mazelib import Maze
from mazelib.generate.Prims import Prims

m = Maze()
m.generator = Prims(27, 34)
m.generate()
```

That's to generate a maze.  Did it work? 

Are you trying to display a maze?  We have docs for that too:

https://github.com/john-science/mazelib/blob/master/docs/EXAMPLES.md

If the above worked, perhaps it's as easy as:

```python
print(m)
```

**Comment by comalley29** [comment]
I've managed to generate a maze, I tested printing it as plain text first that worked, but I need to print as a PNG, when we try the PNG code we get an error showPNG is missing argument grid, thank you.

**Comment by john-science** [comment]
Hello again!

For future reference, the ability for me (or anyone) to help you with a software problem increases 100% if you copy/paste two things:

1. Exactly what you typed.
2. Exactly the error message you got.

It is a little hard for me to know what bug you're seeing from your description.

Let me guess that you are following this example for the `showPNG()` function:

https://github.com/john-science/mazelib/blob/master/docs/EXAMPLES.md#example-2-plotting-the-maze-with-matplotlib

If that is the case, you just need to run this code:

```python
import matplotlib.pyplot as plt

from mazelib import Maze
from mazelib.generate.Prims import Prims

def showPNG(grid):
    """Generate a simple image of the maze."""
    plt.figure(figsize=(10, 5))
    plt.imshow(grid, cmap=plt.cm.binary, interpolation='nearest')
    plt.xticks([]), plt.yticks([])
    plt.show()

m = Maze()
m.generator = Prims(27, 34)
m.generate()

showPNG(m)
```

That should work. If it doesn't, what error do you get?

Maybe you need to install `matplotlib`? That is the library I use in that example to create PNG files.  You might need to `pip install matplotlib` on the commandline, but that depends on your setup.

**Comment by john-science** [comment]
@comalley29 Were you able to solve your problems with Mazelib?  If so, I would like to close this ticket.

**Comment by comalley29** [comment]
All sorted thank you very much.
