### ISSUE TITLE
Release a version to PyPI supporting 3.11

### ISSUE THREAD

**Issue by john-science** [john-science/mazelib#137]
mazelib actually already supports Python v3.11.

But I hadn't released a new version to pypi.org, because there haven't been any real improvements to the codebase lately.  So, maybe I should squash a ticket and do a release.

**Comment by noah-hein** [comment]
@john-science did you publish mazelib-alt?

**Comment by john-science** [comment]
@noah-hein I did not publish `mazelib-alt`.  I've been trying to figure out who did, to see what changes they want in `mazelib`, but I can't find the person.

> If anyone knows who built `mazelib-alt`, introduce me to them. I'd be happy to update `mazelib` with whatever they need.

**Comment by john-science** [comment]
I am hoping to release an updated 3.11-friendly version of `mazelib` today.

But I am running into the problem that I can't convert my `mazelib-0.9.14-cp39-cp39-linux_x86_64.whl` linux wheel into a "manylinux" wheel, because the program that does that (`auditwheel`) requires `patchelf >= 0.14`, and I can only get `patchelf == 0.10` on Ubuntu.

Here are some references to this issue:  https://github.com/pypa/auditwheel/issues/174

**Comment by john-science** [comment]
`mazelib` is now available for Python3.11 natively on PyPI.org!

https://pypi.org/project/mazelib/0.9.14/#files
