### ISSUE TITLE
Expand to 3D?

### ISSUE THREAD

**Issue by ethindp** [john-science/mazelib#141]
Not sure how easy this would be, but could you add 3D versions of the algorithms in this library? Might be a bit of a research topic at first.

**Comment by john-science** [comment]
This is an interesting idea. I have thought of it in the past, but never tried implementing it.

Some thoughts:

1. This might mean a BIG change to the mazelib API, to allow for the choice of 2D/3D.
2. This would mean at least a surface-level re-write of every algorithm, if we made the choice of 2D/3D optional on every algorithm.
3. This would mean, as you say, some actual research into the algorithms.  I wonder which would be easier or harder than others!  That would be very interesting to find out.

I'm not against it, but much research is needed first, as it would be a large systematic change to the codebase.  Or... maybe we just have optional 3D-only algorithms?  That seems clunky.

**Comment by ethindp** [comment]
@john-science In response to your points:

1. I don't think a big API change will be required. Though it might be algorithm-dependent. But looking at the abstract class for `MazeGenAlgo`, I think that you'd only have to change `__init__` to except a `d` parameter that can default to `0` (no 3D component), `generate` to return a 2D or 3D grid depending on `self.d`, and `_find_neighbors` to accept not only `r` and `c` but also `l` (level). (It might be easier just to change `r` and `c` to `x` and `y`, come to think of it.)
2. Yes, a surface-level rewrite would be necessary, since you'd be dealing with an optional extra coordinate. But unless the algorithm is dramatically different when expanded to higher dimensions, I can't imagine the rewrite to be too deep. If you just create a flat array with `x*y*z` elements, every coordinate would still be a cell, so, theoretically, the algorithm should function similarly, if not identically, on an n-dimensional grid. If this hypothesis holds, then you could, theoretically, expand the library to create N-dimensional grids, assuming `N>=2` (since `N=1` would be... Kinda useless).
3. Yes, definitely a research project. Creating 3D specific algorithms would be interesting, for sure, since you have a lot more possibilities. But I don't think it'd be all that worth it unless you incorporated something like wave function collapse (if you could alter that to generate grids instead of images).

If you can, I'd recommend you check out chapter 13 of "Mazes for Programmers: Code Your Own Twisty Little Passages" (which is where most of these algorithms come from, or, at least, they're well-documented in that book). It discusses this topic in detail. The book uses Ruby, but that shouldn't be too tricky to translate to idiomatic Python.

**Comment by john-science** [comment]
Oddly, I think one of the first things I would do is come up with a way to visualize a 3D maze. 

While that's not necessary, while building a new maze generating algorithm, I tend to make a lot of plots to see if the mazes look right. Some times there are little flaws or skews to special cases in the algorithm that the human eye can spot immediately.

Off hand, I think visualizing a 3D maze will be a bit inconvenient.  But... I bet someone has done something similar before I can copy.  Hopefully, not much research is needed there.

**Comment by john-science** [comment]
I'll be honest, this idea is neat, but after investigating, it would be a nearly 100% re-write of the library.  And I doubt anyone would use the feature, as 3D mazes are hard on the poor human brain.

Unless there is a _lot_ of interest, I won't to do this.  

If enough people comment on this ticket, I will reopen it.
