### ISSUE TITLE
Collision Solve Algorithm crashes when generating a maze using CellularAutomaton

### ISSUE THREAD

**Issue by Thrywyn** [john-science/mazelib#145]
I tried generating a maze using the CellularAutomaton generator and solving it using the Collision solver. It results in a typeError.

Here is the relevant code: 

```python
m = Maze()
m.generator = CellularAutomaton(100, 100, 1, 1)
m.generate()
m.start = (1, 1)
m.end = (199, 199)
m.solver = Collision()
m.solve()
```

Error:  
```
 in main  
    m.solve()  
  File "C:\Python311\Lib\site-packages\mazelib\mazelib.py", line 216, in solve  
    self.solutions = self.solver.solve(self.grid, self.start, self.end)  
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Python311\Lib\site-packages\mazelib\solve\MazeSolveAlgo.py", line 20, in solve  
    return self._solve()  
           ^^^^^^^^^^^^^  
  File "C:\Python311\Lib\site-packages\mazelib\solve\Collision.py", line 34, in _solve  
    paths = self._flood_maze(start)  
            ^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Python311\Lib\site-packages\mazelib\solve\Collision.py", line 62, in _flood_maze  
    temp_paths = self._one_time_step(paths)  
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Python311\Lib\site-packages\mazelib\solve\Collision.py", line 84, in _one_time_step  
    ns = self._find_unblocked_neighbors(path[-1])  
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Python311\Lib\site-packages\mazelib\solve\MazeSolveAlgo.py", line 64, in _find_unblocked_neighbors  
    r, c = posi  
    ^^^^  
TypeError: cannot unpack non-iterable NoneType object  
```

**Comment by john-science** [comment]
Well, I tried this once, and it worked fine.  (For print out purposes, I'll show a smaller example, but it worked with your exact case as well.)

```python
from mazelib import Maze
from mazelib.generate.CellularAutomaton import CellularAutomaton
from mazelib.solve.Collision import Collision

m = Maze()
m.generator = CellularAutomaton(10, 10, 1, 1)
m.generate()
m.start = (1, 1)
m.end = (19, 19)
m.solver = Collision()
m.solve()

print(m)
```

Yielded:

```bash
#####################
#S++++  #         # #
### #+### ##### ### #
# # #+#   # # # #   #
# # #+# ### # # # # #
# # #+# #     # # # #
# # #+# ### # # ### #
# # #+#   # # #     #
# # #+### # ### #####
# # #+++# #         #
# # # #+# ### #######
# # # #+#   # #     #
# ### #+### ### #####
#     #+++#     #   #
####### #+### # ### #
#       #+  #       #
# ### ###+### ##### #
# # # #  +#   #+++# #
# # ### #+#####+#+# #
# #     #+++++++#++E#
#####################
```

So, as anticipated, this worked fine.

It IS possible that if I run this a million times:

1. Maybe `CellularAutomaton` occasionally generates a maze with no solution.
2. Maybe `Collision` occasionally fails.

This is definitely a floating ("sometimes") problem though. Let me script it up and see if I can reproduce it.

**Comment by john-science** [comment]
# Documentation

Okay!

The `mazelib` docs for the `CellularAutomaton` algorithm generates imperfect mazes:

https://github.com/john-science/mazelib/blob/9d1fd785fc42f5c0139122197987e25dd2cdc8d4/docs/MAZE_GEN_ALGOS.md?plain=1#L88-L90

For instance, notice on the example maze I printed out in my last example at `(15, 15)` or so, there is a single-column wall surrounded by all open hallways.  So, that maze includes a loop.  This means the maze doesn't have "just one and only one" solution: it is an "imperfect" maze.

# THE PROBLEM

The `Collision` solver says it works against imperfect mazes:

https://github.com/john-science/mazelib/blob/9d1fd785fc42f5c0139122197987e25dd2cdc8d4/docs/MAZE_SOLVE_ALGOS.md?plain=1#L48-L51

But clearly it doesn't.

I only had to run a few thousand random examples from your code above to prove this.  

Essentially, the `Collision` solver only _usually_ works against imperfect mazes. However, it fails if there is one of these loops and that loop TOUCHES the shortest path solution through the maze.  In this case, it fails.

# SOLUTION

1. I will update the docs so they say the `Collision` solver won't necessarily work against imperfect mazes.
2. If you want to keep using the `CellularAutomaton` generate, you will have to use one of these solvers:
    - `Chain`
    - `RandomMouse`
    - `BacktrackingSolver`
    - `ShortestPath`
    - `ShortestPaths`
    - `Trémaux`

**Comment by john-science** [comment]
Okay, I updated the documentation on the `Collision` solver:

https://github.com/john-science/mazelib/commit/053aefb2c4a56685e0991ebb47a4b00eb00a5d4b

And I am closing this ticket.

Thanks!
