### ISSUE TITLE
Import error in setup.py

### ISSUE THREAD

**Issue by aniketsharma00411** [john-science/mazelib#148]
Hi, the [setup.py](https://github.com/john-science/mazelib/blob/main/setup.py) uses os.path at lines 79 and 81 and it is giving an error because the same has not been imported. I know you are planning a move to pyproject.toml (#139) but it is a quick fix.

**Comment by aniketsharma00411** [comment]
I can do it if you are okay with it. Also would love to help with other issues too. Let me know and we can discuss things.

**Comment by john-science** [comment]
Okay, the fix is in place.

Sorry it took so long.  And I guess I need to look in the git history and figure out when and how this happened.
