### ISSUE TITLE
ModuleNotFoundError: No module named 'mazelib.generator'

### ISSUE THREAD

**Issue by wer310** [john-science/mazelib#151]
```
ModuleNotFoundError: No module named 'mazelib.generator'
```

**Comment by wer310** [comment]
I have a module

**Comment by john-science** [comment]
> I have a module

Are you saying the problem is resolved?

If not, can you give me two things:

1. **Information about your system**: OS version, Python version
2. **Copy/Paste** the screenshot of what you typed to get this.

**Comment by john-science** [comment]
I will close this ticket, as I never understood the question.

Feel free to ask for more help, or give me a stack trace so I can see your issue.
