### ISSUE TITLE
Latest PyPi version is not compatible with Python 3.12

### ISSUE THREAD

**Issue by ethindp** [john-science/mazelib#152]
Python 3.12 and later are not supported, and attempting to build it yields compilation errors with NumPy (it wants to build 1.16 but 1.26 has a wheel).

**Comment by john-science** [comment]
Right, the `mazelib` install explicitly bars installing on Python 3.12.  This is clearly called out on pypi.org.  So, this isn't a surprise. Sorry if it's a problem for you though.  It can be fixed.

It'll be a big lift. Annoyingly, both NumPy and Cython had big changes in Python 3.12, so supporting it will be work. And it'll be _real_ hard to support Python 3.7 and 3.8 along with 3.12.

But, okay, if I have a user base that is interested in 3.12, then it's time.
