### ISSUE TITLE
Code gets infinitely stuck depending on the start or end position

### ISSUE THREAD

**Issue by gbhardwaj00** [john-science/mazelib#159]
For my case, m.start is set to [0, 0] and m.end is set to [19,19]. This is for a 20*20 maze

Whenever the `S` and `E` are trapped inside the walls, for example `S` at [0, 0] has walls in the SouthEast directions, it gets stuck and do not show an error.

Code used:

```python
# Using mazelib API to generate a maze for our inputs
# Source : https://github.com/john-science/mazelib
from mazelib import Maze
from mazelib.solve.BacktrackingSolver import BacktrackingSolver
from mazelib.generate.DungeonRooms import DungeonRooms

import numpy as np

if __name__ == '__main__':
    m = Maze()
    m.generator = DungeonRooms(5, 5)
    m.generate()

    print ("Maze\n", m.tostring())

    m.solver = BacktrackingSolver()
    m.start = (0, 0)
    m.end = (3, 0)
    print ("Maze with Entarnces\n", m.tostring(True))
    
    m.solve()

    # dungeon_maze = np.array(m.grid, dtype=np.uint8)
    print("Solution\n", m.tostring(True, True))
    # dungeon_maze.tofile('maze.bin')     
```

It gets stuck at `m.solve()` step. Pardon if this is a known issue.

**Comment by john-science** [comment]
Thanks for your comment!

As it happens, your start and end points are not valid:

```python
    m.start = (0, 0)
    m.end = (3, 0)
```

You should try to plot that. You would find that those are both in the middle of walls. They are NOT in open hallways.

So, if you were to do this, it would work fine:

```python
    m.start = (1, 1)
    m.end = (3, 1)
```

For the problem you lay out, you will find that if you keep all your numbers _odd_, you will always be in a hallway.

Thanks!

**Comment by gbhardwaj00** [comment]
Hey @john-science , thanks for the reply. My concern was that instead of notifying the user that no path exists, it does not produce an output. It is alright if that is what the program expects. Thanks!
